#!/bin/bash

command -v yq >/dev/null 2>&1 || { echo >&2 "Script requires 'yq' but it is not available."; exit 1; }
command -v curl >/dev/null 2>&1 || { echo >&2 "Script requires 'curl' but it is not available."; exit 1; }

function getAccessToken () {
  if [ ! -z "${1}" ] && [ ! -z "${2}" ] && [ ! -z "${3}" ]; then 
    local content_type='Content-Type: application/json'
    local http_method='POST'
    local request_url="${1}/oauth/token"
    local request_body="{ \"grant_type\":\"client_credentials\",\"client_id\":\"${2}\",\"client_secret\":\"${3}\" }"
    local response=`curl -H "$content_type" -X "$http_method" -d "$request_body" $request_url 2>/dev/null`
    echo $response | yq '.access_token'
  else 
    return 1
  fi
}

function createNewProject () {
  if [ ! -z "${1}" ] && [ ! -z "${2}" ] && [ ! -z "${3}" ]; then 
    local project_name="${3}"
    local auth_header="Authorization: Bearer $2"
    local content_type='Content-Type: application/json'
    local http_method='POST'
    local request_url="${1}/v1/projects"
    local request_body="{ \"name\":\"${project_name}\" }"
    local response=`curl -H "$content_type" -H "$auth_header" -X "$http_method" -d "$request_body" $request_url 2>/dev/null`
    echo $response | yq '.uuid'
  else 
    return 1
  fi
}

function getOrCreateNewProject () {
  if [ ! -z "${1}" ] && [ ! -z "${2}" ] && [ ! -z "${3}" ]; then 
    local project_name="${3}"
    local auth_header="Authorization: Bearer $2"
    local content_type='Content-Type: application/json'
    local http_method='GET'
    local request_url="${1}/v1/projects"
    local response=`curl -H "$content_type" -H "$auth_header" -X "$http_method" $request_url 2>/dev/null`
    local project_id=`echo ${response}|project_name="${3}" yq 'filter(.name == strenv(project_name))'|yq '.[].uuid'`

    if [ -z "${project_id}" ]; then
      project_id=`createNewProject "${1}" "${2}" "${project_name}"`
      execution_id=`createNewExecution "${1}" "${2}" "${project_id}"`
      echo "${project_id}"
    else
      echo "${project_id}"
    fi
  else 
    return 1
  fi
}

function createNewExecution () {
  if [ ! -z "${1}" ] && [ ! -z "${2}" ] && [ ! -z "${3}" ]; then 
    local auth_header="Authorization: Bearer $2"
    local content_type='Content-Type: application/json'
    local http_method='POST'
    local request_url="${1}/v1/projects/${3}/executions"
    local execution_notes='<p><span class=\"text-gray-700\">Autogenerated execution</span></p>'
    local request_body="{ \"notes\":\"$execution_notes\" }"
    local response=`curl -H "$content_type" -H "$auth_header" -X "$http_method" -d "$request_body" $request_url 2>/dev/null`
    echo $response | yq '.uuid'
  else 
    return 1
  fi
}

api_base_path="${LOADGENERATOR_APIBASEURL}"
if [ -z "${api_base_path}" ] || [ "${api_base_path}" = 'null' ]; then echo >&2 "Can't determine api_base_path"; exit 1; fi

api_client_id="${LOADGENERATOR_APICLIENTID}"
if [ -z "${api_client_id}" ] || [ "${api_client_id}" = 'null' ]; then echo >&2 "Can't determine api_client_id"; exit 1; fi

api_client_secret="${LOADGENERATOR_APICLIENTSECRET}"
if [ -z "${api_client_secret}" ] || [ "${api_client_secret}" = 'null' ]; then echo >&2 "Can't determine api_client_secret"; exit 1; fi

access_token=`getAccessToken "$api_base_path" "$api_client_id" "$api_client_secret"`
if [ -z "${access_token}" ] || [ "${access_token}" = 'null' ]; then echo >&2 "Can't determine access_token"; exit 1; fi

project_name="$1"
if [ -z "${project_name}" ] || [ "${project_name}" = 'null' ]; then echo >&2 "Can't determine project_name"; exit 1; fi

project_id=`getOrCreateNewProject "$api_base_path" "$access_token" "$project_name"`
if [ -z "${project_id}" ] || [ "${project_id}" = 'null' ]; then echo >&2 "Can't determine project_id"; exit 1; fi

echo "$project_id"
